# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: Environment Data Science
email: info@env-data-sci.com
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/EnvDataSci
  - title: Google+
    url: https://plus.google.com/b/107826369878870426241/107826369878870426241
  - title: LinkedIn
    url: https://www.linkedin.com/company/environment-data-science
